import { ButtonOptions } from '../utils/buttonOptions'
import { ShowAlertOptions } from '../utils/showAlertOptions'

export const values = {
  button: ButtonOptions.image,
  setButton: jest.fn(),
  name: '',
  setName: jest.fn(),
  html: '',
  setHtml: jest.fn(),
  chooseFile: jest.fn(),
  file: '',
  text: '',
  setText: jest.fn(),
  conditions: { simpleStatements: [], operator: '' },
  setConditionsFunction: jest.fn(object => object),
  handleToggleOperator: jest.fn(object => object),
  textValidate: [],
  showAlert: ShowAlertOptions.alertError,
  handleCloseAlert: jest.fn(),
  nameProducts: [{ label: 'product', value: 'valueProduct' }],
  nameSku: [{ label: 'sku', value: 'valueSku' }],
  nameBrands: [{ label: 'brand', value: 'valueBrand' }],
  nameCollections: [{ label: '', value: '' }],
  nameCategory: [{ label: '', value: '' }],
  nameSpecification: [{ label: '', value: '' }],
  setConditions: jest.fn(),
  valuesSearchBadges: [],
  listBadgesEdit: [
    {
      id: '0',
      name: 'listBadges0',
      type: 'string',
      index: 0,
    },
    {
      id: '1',
      name: 'listBadges1',
      type: 'string',
      index: 1,
    },
    {
      id: '2',
      name: 'listBadges2',
      type: 'string',
      index: 2,
    },
    {
      id: '3',
      name: 'listBadges3',
      type: 'string',
      index: 3,
    },
    {
      id: '4',
      name: 'listBadges4',
      type: 'string',
      index: 4,
    },
    {
      id: '5',
      name: 'listBadges5',
      type: 'string',
      index: 5,
    },
    {
      id: '6',
      name: 'listBadges6',
      type: 'string',
      index: 6,
    },
  ],
  deleteBadges: jest.fn(),
  modalDelete: false,
  setModalDelete: jest.fn(),
  clickDelete: jest.fn(),
  editBadges: jest.fn(),
  clickEdit: jest.fn(),
  setModalEdit: jest.fn(),
  modalEdit: false,
  showImage: false,
  setShowImage: (value: boolean) => {
    !value
  },
  clearValue: jest.fn(),
  save: jest.fn(),
  paginations: {
    currentPage: 2,
    currentItemFrom: 5,
    currentItemTo: 10,
    tableLength: 5,
  },
  setPaginationFunction: jest.fn(),
  sizeOfAllBadgesIndexed: 16,
}
